### ISSUE TITLE
The problem of multi frame training

### ISSUE THREAD

**Issue by Wzh-42** [KHB1698/DC-GCT#3]
Thanks for your work!
when I train:
python main.py --train  --frames 9  or more
The assertionError is as follows：
“
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    loss = train(opt, actions, train_dataloader, model, optimizer, epoch)
  File "main.py", line 25, in train
    return step('train', opt, actions, train_loader, model, optimizer, epoch)
  File "main.py", line 48, in step
    loss = mpjpe_cal(output_3D, out_target)
  File "/root/autodl-tmp/DC-GCT/common/utils.py", line 21, in mpjpe_cal
    assert predicted.shape == target.shape
AssertionError
”

How should I handle it？Thanks!

**Comment by KHB1698** [comment]
Sorry, we do not provide multi-frame training for the time being. But for your problem, you can download our latest version again, we are using weighted_mpjpe loss function. You can also comment out the line 'assert predict.shape == target.shape', which might solve your confusion.
